import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Audience-first IA (roadmap #113), two top-level sections:
 *
 *   1. Start here       — orientation: intro, the zero-cost quickstart, the glossary.
 *   2. Using DIG        — one sub-category per AUDIENCE. Each audience's landing doc
 *                         carries the 10-second "why" + the mental model, then the
 *                         high-signal task-oriented how-to (linking the existing
 *                         CLI/SDK/RPC pages). This replaces the old "Documentation".
 *   3. Protocol deep-dive — the full normative design (the format/* internals, the
 *                         RPC/protocol specs, and CHIP-0035),
 *                         collapsed by default. Replaces the old "DigStore" + Protocol
 *                         + RPC-internals groups. "Support" folds into the
 *                         Troubleshooting audience in Section 2.
 *
 * Doc IDs are listed explicitly (not autogenerated by folder) so each task-oriented
 * how-to page can live beside the audience that needs it while the same underlying
 * file is reused by the Protocol deep-dive for its normative angle — no files move,
 * so the dense web of relative links between pages stays intact.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Start here',
      collapsible: true,
      collapsed: false,
      items: ['intro', 'quickstart', 'concepts'],
    },
    {
      type: 'category',
      label: 'Using DIG',
      collapsible: true,
      collapsed: false,
      link: {type: 'doc', id: 'audiences/app-developers'},
      items: [
        {
          type: 'category',
          label: 'App developers',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'audiences/app-developers'},
          items: [
            'journeys/hub-user',
            'journeys/connect-your-wallet',
            'journeys/digstore-cli',
            'quickstart',
            'digstore/cli/install',
            'digstore/cli/quickstart',
            'digstore/cli/project-workflow',
            'build-a-dapp/scaffold',
            'digstore/cli/configuration',
            'digstore/cli/onchain-anchoring',
            'digstore/cli/sharing',
            'build-a-dapp/tip-your-store',
            'build-a-dapp/submit-to-the-store',
            'digstore/cli/deploy-from-github-actions',
            'automation/deploy-keys',
            'automation/webhooks',
          ],
        },
        {
          type: 'category',
          label: 'NFT developers',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'audiences/nft-developers'},
          items: [
            'build-a-dapp/scaffold',
            'digstore/cli/command-reference',
            'spends',
            'sdk',
          ],
        },
        {
          type: 'category',
          label: 'Integration developers',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'audiences/integration-developers'},
          items: [
            'journeys/integrate',
            'build-a-dapp/tutorial',
            'build-a-dapp/example-gallery',
            'sdk',
            'browser/using-window-chia',
            'browser/window-chia-reference',
            'browser/wallet-security',
            'rpc/what-is-the-dig-rpc',
            'rpc/methods',
            'rpc/streaming',
            'rpc/public-network-rpc',
            'digstore/cli/streaming-and-keys',
            'spends',
            'machine-surfaces',
            'digstore/cli/deploy-from-github-actions',
            'automation/deploy-keys',
            'automation/webhooks',
            'support/error-codes',
          ],
        },
        {
          type: 'category',
          label: 'Node operators',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'run-a-node/index'},
          items: [
            'run-a-node/index',
            'run-a-node/apt',
            'run-a-node/universal-installer',
            'run-a-node/point-a-consumer',
            'run-a-node/configure',
            'run-a-node/run-a-relay',
            'rpc/dig-remote',
            'rpc/conformance',
            'run-a-node/manage',
          ],
        },
        {
          type: 'category',
          label: 'Content consumers',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'audiences/content-consumers'},
          items: [
            'browser/chia-protocol',
            'browser/using-window-chia',
            'browser/wallet-security',
            'run-a-node/point-a-consumer',
          ],
        },
        {
          type: 'category',
          label: 'Troubleshooting',
          collapsible: true,
          collapsed: true,
          link: {type: 'doc', id: 'audiences/troubleshooting'},
          items: [
            'support/troubleshooting',
            'support/error-codes',
            'support/faq',
            'support/get-help',
            'support/status',
            'support/changelog',
          ],
        },
      ],
    },
    {
      // The pure, first-class protocol specification — SEVEN layers, bottom-up,
      // with the implementation as the source of truth. Each spec page names its
      // canonical crate/file. The dig RPC + §21 transport are the protocol's
      // machine interface and live here too.
      // The task-oriented format/RPC/CLI pages are kept under "Reference & guides"
      // so the dense cross-link web between docs stays intact.
      type: 'category',
      label: 'Protocol',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'protocol-deep-dive'},
      items: [
        'protocol-deep-dive',
        'protocol/identity-and-naming',
        'protocol/urn-and-addressing',
        'protocol/cryptography',
        'protocol/merkle-proofs',
        'protocol/bls-signatures',
        'protocol/capsule-format',
        'protocol/self-defending-module',
        'protocol/on-chain-anchoring',
        'protocol/dig-cat-payment',
        'protocol/dig-rpc',
        'protocol/transport-and-push',
        'protocol/peer-network',
        'protocol/onion-routing',
        'protocol/verification-and-provenance',
        'protocol/blind-host-model',
        'protocol/conformance-and-parity',
        {
          type: 'category',
          label: 'Reference & guides',
          collapsible: true,
          collapsed: true,
          items: [
            'concepts',
            'digstore/format/store-structure',
            'digstore/what-is-digstore',
            'digstore/format/overview',
            'digstore/format/urns-and-encryption',
            'digstore/format/proofs-and-security',
            'digstore/cli/onchain-anchoring',
            'rpc/what-is-the-dig-rpc',
            'rpc/methods',
            'rpc/conformance',
            'rpc/streaming',
            'rpc/public-network-rpc',
            'inclusion-vs-execution-proofs',
            'rpc/dig-remote',
            'protocol/window-chia-provider',
            'chip-0035-spends-and-delegation',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
