import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Role-based sidebar (roadmap #32).
 *
 * Instead of the flat autogenerated tree, the docs are grouped into four
 * audience tracks so a reader lands next to what THEY need — a deployer is not
 * dropped beside CHIP-0035 internals:
 *
 *   - Start here   — orientation + the zero-cost quickstart + the glossary
 *   - Deploy & host— ship a site/dapp with DigStore + the CLI (deployers — the
 *                    default audience, so this comes first after Start here)
 *   - Build dapps  — read content + the in-browser wallet (integrating devs)
 *   - Run a node   — serve content: install dig-node (apt / universal) + systemd
 *                    (operators — the supply side, beside the deployer tracks)
 *   - Support      — get unstuck
 *   - Protocol     — the full specs (low-prominence; protocol developers)
 *
 * Each track is an explicit category; its members reuse the existing folder
 * categories (whose labels/positions live in `_category_.json`) so we don't
 * move files or break the many relative links between them. Docusaurus expands
 * a directory reference into that folder's `_category_.json`-driven category.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Start here',
      collapsible: true,
      collapsed: false,
      items: ['intro', 'quickstart', 'concepts'],
    },
    {
      // Audience 1 (hub users + frontend deployers) is the default path, so
      // "Deploy & host" comes first after Start here — the core "ship my
      // content" task — before the integrating-developer "Build dapps" track.
      type: 'category',
      label: 'Deploy & host',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Deploy & host',
        description:
          'Ship a site, dapp, or NFT collection to DIG: the DigStore format, the digstore CLI, on-chain anchoring, sharing, and deploying from CI. Build and preview for free; publish a capsule for a flat 100 DIG.',
      },
      items: [{type: 'autogenerated', dirName: 'digstore'}],
    },
    {
      type: 'category',
      label: 'Build dapps',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Build dapps',
        description:
          'For developers wiring DIG into their own apps: follow the end-to-end "Build a dapp" thread, read verified, encrypted content over the dig RPC, and request keys, signatures, and spends from the browser-injected window.chia wallet.',
      },
      items: [
        {type: 'autogenerated', dirName: 'build-a-dapp'},
        {type: 'autogenerated', dirName: 'browser'},
        {type: 'autogenerated', dirName: 'rpc'},
      ],
    },
    {
      // Audience 1 operators: run the SERVE side. Sits after the deployer/dev
      // tracks (you publish/build content, then optionally serve it) and before
      // Support. Listed explicitly (not autogenerated) so the track is one flat
      // level — overview first, then the apt path — with no redundant nesting.
      type: 'category',
      label: 'Run a node',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'run-a-node/index'},
      items: ['run-a-node/apt'],
    },
    {
      type: 'category',
      label: 'Support',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'support'}],
    },
    {
      type: 'category',
      label: 'Protocol',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Protocol',
        description:
          'The deep, normative specifications behind the network — for protocol developers who want the full design. Most builders won’t need them to ship.',
      },
      items: [
        {type: 'autogenerated', dirName: 'protocol'},
        {type: 'autogenerated', dirName: 'whitepapers'},
      ],
    },
  ],
};

export default sidebars;
